
# Time Intervals Example: 1 h, 30 m, 15 m, 5 h...
# Always separate it with a space.

## Garden:
## This will be the initial amount
garden:
  fruits:
    strawberries: 3
    apples: 4
  flowers:
    sunflowers: 3
    roses: 2
    orchids: 2
  decorations:
    benches: 1
  animals:
    dogs: 2
    ducks: 1

# max = maximum instances of fruit spawned
fruits:
  apple:
    max: 5
    respawn_interval: '1 h'
    harvesting_interval: '45 m'
    watering_interval: '4 h'
  strawberry:
    max: 4
    respawn_interval: '35 m'
    harvesting_interval: '30 m'
    watering_interval: '45 m'

flowers:
  sunflower:
    watering_interval: '1 h' 
    pollination_interval: '45 m'
  rose:
    watering_interval: '1 h'
    pollination_interval: '45 m'
  orchid:
    watering_interval: '1 h'
    pollination_interval: '1 h'

decorations:
  bench:
    cleaning_interval: '30 m'

animals:
  dog:
    petting_interval: '15 m'
    feeding_interval: '20 m'
  duck:
    petting_interval: '35 m'
    feeding_interval: '30 m'

users:
  max_users: 4
  max_nickname_length: 15