
# Time Intervals Example: 1 h, 30 m, 15 m, 5 h...
# Always separate it with a space.

garden:
  fruits:
    - 'strawberry:5'
    - 'apple:5'
  flowers:
    - 'sunflower:3'
    - 'rose:5'
    - 'orchid:2'
  decorations:
    - 'bench:1'
  animals:
    - 'dog:1'
    - 'duck:1'

fruits:
  apple:
    harvesting_interval: '45 m'
    watering_interval: '4 h'
  strawberry:
    harvesting_interval: '30 m'
    watering_interval: '45 m'

flowers:
  sunflower:
    watering_interval: '1 h' 
    pollination_interval: '45 m'
  rose:
    watering_interval: '1 h'
    pollination_interval: '45 m'
  orchid:
    watering_interval: '1 h'
    pollination_interval: '1 h'

decorations:
  bench:
    cleaning_interval: '30 m'
    limit: 2

animals:
  dog:
    feeding_interval: '10 m'
  duck:
    feeding_interval: '30 m'

users:
  max_users: 4
  max_nickname_length: 15